# Generated by Django 6.0 on 2025-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="conversational_practice",
            field=models.JSONField(default=list),
        ),
    ]
