# Generated by Django 6.0 on 2025-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach", "0003_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="practice_time_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="words_learned",
            field=models.IntegerField(default=0),
        ),
    ]
