# Generated by Django 6.0 on 2025-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach", "0004_userprogress_practice_time_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
