# Generated by Django 6.0 on 2025-12-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach", "0007_lesson_user_alter_lesson_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, help_text="List of chapters (legacy)"
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True, help_text="Markdown content")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="coach.book",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
