"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# PWA Settings
PWA_APP_NAME = "AI English Coach"
PWA_APP_DESCRIPTION = "Your personal AI English tutor for conversation practice."
PWA_APP_THEME_COLOR = "#6750A4"
PWA_APP_BACKGROUND_COLOR = "#FEF7FF"
PWA_APP_DISPLAY = "standalone"
PWA_APP_ORIENTATION = "portrait-primary"
PWA_APP_START_URL = "/"
PWA_APP_SCOPE = "/"
PWA_APP_ICONS = [
    {
        "src": "/static/icons/icon-72x72.png",
        "sizes": "72x72",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-96x96.png",
        "sizes": "96x96",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-144x144.png",
        "sizes": "144x144",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-192x192.png",
        "sizes": "192x192",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-512x512.png",
        "sizes": "512x512",
        "type": "image/png",
    },
]
PWA_APP_ICONS_APPLE = [
    {
        "src": "/static/icons/icon-192-192.png",
        "sizes": "192x192",
        "type": "image/png",
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": "static/icons/icon-512-512.png",
        "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
    }
]
PWA_APP_DIR = "ltr"
PWA_APP_LANG = "en-US"
PWA_APP_SHORT_NAME = "AI English Coach"
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "static/js/sw.js")




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

GEMINI_API_KEY = env('GEMINI_API_KEY')

ALLOWED_HOSTS = env('ALLOWED_HOSTS').split(',')

# CSRF Configuration
# Automatically trust origins from ALLOWED_HOSTS to fix login errors
# CSRF Configuration
# Automatically trust origins from ALLOWED_HOSTS to fix login errors
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if not CSRF_TRUSTED_ORIGINS and ALLOWED_HOSTS:
    CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS] + [f'http://{host}' for host in ALLOWED_HOSTS]

# Development settings to prevent "CSRF cookie not set"
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False

# Session settings - Never auto-logout
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'pwa',
    'django.contrib.sites',  # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dynamic_preferences',
    'dynamic_preferences.users.apps.UserPreferencesConfig',
    'coach',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware", # Required by allauth
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                "django.template.context_processors.request", # Required by allauth
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SESSION_REMEMBER = True  # Always remember login
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False  # Don't logout on password change
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True  # Auto login after password reset

# Remember me - keep users logged in
REMEMBER_ME_DURATION = 60 * 60 * 24 * 365  # 1 year

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
